name: main
on: [push]
jobs:
  op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: docker/setup-buildx-action@v3
      - run: '"$(wget -O- lesiw.io/op | sh)"'
